### ISSUE TITLE
Update check always shows up to date

### ISSUE THREAD

**Issue by Bluscream** [nixxquality/GitHubUpdate#3]
I don't know why but your sample always returns that i'm up-to date on [my repo](https://github.com/Bluscream/GTACoop/releases/).

**Comment by Rambalac** [comment]
Do you update your assembly version?

**Comment by Rambalac** [comment]
Ah, yeah, it does not check updates.

**Comment by nixxquality** [comment]
I have personally abandoned this project as I no longer use GitHub. Either of you can feel free to fork it.
If you can get it to work again, I'll see about transferring the NuGet package to you.

**Comment by Rambalac** [comment]
it's ok. I already implemented my own.

**Comment by Bluscream** [comment]
@nixxquality Do you know any good alternatives?

**Comment by Rambalac** [comment]
@bluscream https://github.com/Rambalac/ACDDokanNet/blob/master/ACD.DokanNet.Gui/UpdateChecker.cs

**Comment by Bluscream** [comment]
@Rambalac Thanks, will try it :)
